 Program Defined Hot Keys W = Numerical KeyPad (White)  As Of Tue  11-16-93

Shft-Alt-Del(W)       Unload Hookkbsm
Shft-Alt-End(W)       ShutDown System

Shft-Alt-UpArrow(W)   Re-Read HOOKKBSM.DAT into Memory
Shft-Alt-Ins(W)       Open Small OS/2 Window

Shft-Ctl-LeftArrow(W) Start Macro Recording
Shft-Ctl-RghtArrow(W) End Macro Recording & Save to Disk File
Shft-Ctl-Ins(W)       PlayBack Macro Currently in Memory
Shft-Ctl-PgDn(W)      Save Current Loaded Macro to DiskFile
Shft-Ctl-PgUp(W)      Load Selected Macro from Disk to Memory

Shft-Ctl-?            Display User Defined HotKeys (hot-keys.usr)
Shft-Alt-?            Display Prog Defined HotKeys (hot-keys.prg)

Shft-Alt-5(W)         Toggle Hot-Keys Off/On

